# These are supported funding model platforms

github: [ppy]
custom: ['https://osu.ppy.sh/store/products/208']

# although I could use the supporter, I recommend you get it for yourself or for a friend... Either way, you are helping peppy with the development of osu! if you do (I have nothing to do with the development of osu! or anything)
